### ISSUE TITLE
canonical implementation of syntax highlighting

### ISSUE THREAD

**Issue by blaggacao** [keidax/tree-sitter-crystal#1]
similar to this: https://github.com/cstrahan/tree-sitter-nix/tree/master/queries

I wanted to add crystal syntax-highlighting to `helix-editor`

https://github.com/helix-editor/helix/tree/d8df10f2958f70ee84b7c78cb7ea00aa195bc1c5/runtime/queries

**Comment by hugopl** [comment]
Initial work can be found here: https://github.com/keidax/tree-sitter-crystal/pull/17

I plan do to other queries for text-objects, etc... and submit the support to nvim-tree-sitter.

meanwhile to let this work on nvim you do:

1. Clone this repo with the patch in the mentioned PR.
2. Add this lua code somewhere after load nvim-treesitter plugin.
```Lua
local parser_config = require("nvim-treesitter.parsers").get_parser_configs()

parser_config.crystal = {
	install_info = {
		url = "PATH_TO_THIS_REPO",
		files = { "src/parser.c", "src/scanner.c", "src/unicode.c" },
		-- optional entries:
		generate_requires_npm = false, -- if stand-alone parser without npm dependencies
		requires_generate_from_grammar = false, -- if folder contains pre-generated src/parser.c
	},
	filetype = "crystal", -- if filetype does not match the parser name
}
```

3. In nvim: `:TSInstall crystal`
4. `mkdir -p ~/.config/nvim/queries/crystal`
5. Copy the query files, so nvim can find them: `cp PATH_TO_THIS_REPO/queries/*.scm ~/.config/nvim/queries/crystal`
